/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:d9c9d5d1-76c9-4992-b284-fbb098d6371e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_3m61mVneX",
    "aws_user_pools_web_client_id": "5oql32gsd673g122e8gvgdhaa1",
    "oauth": {},
    "aws_user_files_s3_bucket": "aroawsamplify4995388cfcfd43a188f6c82490e85750202220-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://7dh65zvrpfdcddywjoaljtp55i.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
